Spring:
    profiles:
    active:
    - dev
---
Spring:
    profiles: dev 
    application:
        name: mycloud-config-cgenh-dev
---
Spring:
    profiles: test 
    application:
        name: mycloud-config-cgenh-test
